### PR TITLE
Update Debian versions used for AMIs

### PR DESCRIPTION
**Pull request by mcdonnnj**
#  #

## 🗣 Description ##

This pull request updates the versions of Debian used as a base for our AMIs like so:

- `bastion` from [Buster] to [Bullseye]
- `dashboard` from [Stretch] to [Buster]
- `docker` from [Stretch] to [Bullseye]
- `mongo` from [Stretch] to [Buster]
- `nmap` from [Buster] to [Bullseye]
- `nessus` from [Buster] to [Bullseye]
- `reporter` from [Stretch] to [Buster]

The following packages on [Buster] instances are installed from `buster-backports` instead of the normal `buster` repository:

- [awscli]
- [python3-botocore]

Last any AMIs built off of [Buster] have an additional configuration option to the Ansible provisioners to use the `auto_legacy_silent` flag to force preferring Python 2 over Python 3.

## 💭 Motivation and context ##

Debian Stretch has been out of any kind of support since June 30, 2022 per the [LTS schedule page](https://wiki.debian.org/LTS). Unfortunately due to Python 2 requirements the newest version of Debian that most [Stretch] images could move to is [Buster] due to availability of dependent Python 2-based packages available from the respective version repositories. So that we can support [IMDSv2](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html) we install [awscli] and [python3-botocore] from [Backports] on [Buster]-based images.

## 🧪 Testing ##

Automated tests pass. I have verified that these image configurations can build and deploy successfully in my testing environment.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All new and existing tests pass.

[Stretch]: https://www.debian.org/releases/stretch/
[Buster]: https://www.debian.org/releases/buster/
[Bullseye]: https://www.debian.org/releases/bullseye/
[Backports]: https://backports.debian.org/
[awscli]: https://packages.debian.org/buster-backports/awscli
[python3-botocore]: https://packages.debian.org/buster-backports/python3-botocore

### CODE REVIEW

**Review by jsf9k — COMMENTED** [review]
Is there a reason why the Buster-based instances can't use an ED25519 key?

**Comment by mcdonnnj** [comment]
> Is there a reason why the Buster-based instances can't use an ED25519 key?

Is there something I missed?

```console
$ git switch improvement/update_debian_versions
Switched to branch 'improvement/update_debian_versions'
Your branch is up to date with 'origin/improvement/update_debian_versions'.
$ grep -rin temporary_key_pair_type
packer/reporter.json:45:      "temporary_key_pair_type": "ed25519",
packer/docker.json:45:      "temporary_key_pair_type": "ed25519",
packer/mongo.json:45:      "temporary_key_pair_type": "ed25519",
packer/nmap.json:45:      "temporary_key_pair_type": "ed25519",
packer/nessus.json:45:      "temporary_key_pair_type": "ed25519",
packer/dashboard.json:45:      "temporary_key_pair_type": "ed25519",
packer/bastion.json:45:      "temporary_key_pair_type": "ed25519",
```

**Comment by jsf9k** [comment]
> > Is there a reason why the Buster-based instances can't use an ED25519 key?
> 
> Is there something I missed?
> 
> ```
> $ git switch improvement/update_debian_versions
> Switched to branch 'improvement/update_debian_versions'
> Your branch is up to date with 'origin/improvement/update_debian_versions'.
> $ grep -rin temporary_key_pair_type
> packer/reporter.json:45:      "temporary_key_pair_type": "ed25519",
> packer/docker.json:45:      "temporary_key_pair_type": "ed25519",
> packer/mongo.json:45:      "temporary_key_pair_type": "ed25519",
> packer/nmap.json:45:      "temporary_key_pair_type": "ed25519",
> packer/nessus.json:45:      "temporary_key_pair_type": "ed25519",
> packer/dashboard.json:45:      "temporary_key_pair_type": "ed25519",
> packer/bastion.json:45:      "temporary_key_pair_type": "ed25519",
> ```

No, it is I who missed something.  My apologies.

**Review by jsf9k — APPROVED** [review]

**Review by dav3r — APPROVED** [review]
👍 👍 🚀

**Pull request merged**
