### PR TITLE
Fix cyhy-feeds cron job

### PR DESCRIPTION
**Pull request by mcdonnnj**
# 

## 🗣 Description
This fixes the `cron` job for `cyhy-feeds` to start at 00:00 UTC instead of 08:15 UTC to align with the time window used when the `cyhy-data-extract` script is run.

This PR aligns with updates to the `cyhy-data-extract` script in https://github.com/cisagov/cyhy-feeds/pull/37

## 💭 Motivation and Context
Concerns were raised that the `cyhy-data-extract` script was either filtering or missing data in it's export. Upon investigation I realized that the start time for the script was over eight hours after the end of the time window being used. Since CyHy runs continuously it resulted in records being updated with new last time changed values that were past the end fo the query window. If a record had this happen repeatedly either due to happenstance or scan windows there was the possibility that it would never be included in a data extraction. This change has the script start at midnight to align with the end fo the query time window.

## 🧪 Testing
Manually modified production environment to use these new parameters for the `cron` job. Confirmed output is as expected.

## 🚥 Types of Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (causes existing functionality to change)

## ✅ Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by jsf9k — APPROVED** [review]
Three huzzahs for these changes!

**Review by dav3r — APPROVED** [review]
Thanks for investigating this and coming up with an excellent solution @mcdonnnj!  🎸 

My only thought is that we should update the comments to mention the timing issue that led to this change, so that we don't forget (and future developers understand) why we run this at midnight.  

Also, I just noticed that the [existing comment](https://github.com/cisagov/cyhy_amis/blob/2e52defb2d7239bebddbe4bd4a1bdbd5d50621fc/ansible/roles/cyhy_feeds/tasks/main.yml#L93) needs to be updated from "0815 (UTC)" to "0000 (UTC)".

**Comment by jsf9k** [comment]
> My only thought is that we should update the comments to mention the timing issue that led to this change, so that we don't forget (and future developers understand) why we run this at midnight.

Excellent point @dav3r!  I think a description of the timing issue is also in order, since it took us a while to figure that out.

**Review by dav3r — APPROVED** [review]
Stellar comment sir 👍

**Review by jsf9k — APPROVED** [review]
:1st_place_medal:

**Pull request merged**
