### PR TITLE
Add cloud-init code to set hostnames to match private DNS entries

### LINKED ISSUE #56: Set instance hostnames to match their private DNS entries
I'd be nice if the hostnames matched the private DNS.   This will probably involve some cloud-init fu as it seems to be setting the hostname at boot using its own AWS sauce.  

Here's a little ditty that works on the Debian boxes:
```
sudo hostnamectl set-hostname `host \`hostname -I | head -n1\` | awk '{print $5}'`
```

### PR DESCRIPTION
**Pull request by jsf9k**
This pull request improves quality of life a bit by setting the hostnames of the EC2 instances to `bastion`, `database1`, etc. as appropriate.  It is also a stepping stone toward my goal of being able to resolve `database1.cyhy` from `docker.bod` so that I don't need to pass the database IP to `docker.bod`'s Ansible.

This pull request resolves #56.

### CODE REVIEW

**Comment by jsf9k** [comment]
This is working, but I want to do more testing to make sure it is solid before requesting review.

**Comment by jsf9k** [comment]
This pull request **introduces 1 alert** when merging 30d0a4f7f03d54d448920ea2b6937d3fd2b12e05 into bf32d9c380de74cf654686b7fdb2795f4761b8c0 - [view on LGTM.com](https://lgtm.com/projects/g/cisagov/cyhy_amis/rev/pr-598a11e26166d188a0309d6e710f7656fa2f0a7d)

**new alerts:**

* 1 for Syntax error

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by jsf9k** [comment]
This is looking solid now.  I was seeing some inconsistent behavior last night, but that appears to have gone away with commits 9f80826 and 20d7f48.

**Review by dav3r — APPROVED** [review]
Excellent improvements in here @jsf9k.  I didn't see anything that looked wrong, so I'm sure Everything Is Fine™️ (probably). ☁️

**Pull request merged**
