### PR TITLE
Add ClamAV to CyHy Images

### LINKED ISSUE #313: Add ClamAV to CyHy AMIs
# 🚀 Feature Proposal #

Add ClamAV to the CyHy AMIs via [cisagov/ansible-role-clamav](https://github.com/cisagov/ansible-role-clamav).

## Motivation ##

The security folks have been asking for this, and it's an easy thing for us to do for them.

### PR DESCRIPTION
**Pull request by mcdonnnj**
#  #

## 🗣 Description ##

This PR updates the playbook for Packer to install [ClamAV](https://www.clamav.net/) on all images using [cisagov/ansible-role-clamav](https://github.com/cisagov/ansible-role-clamav).

## 💭 Motivation and context ##

This is to resolve #313.

## 🧪 Testing ##

I was able to build all of the images and deploy them to my testing environment. When using the [cisagov/clamav-report](https://github.com/cisagov/clamav-report) tool I can see that scanning has occurred.

Inventory file:

```ini
[bod]
bastion.mcdonnnj.bod
docker.mcdonnnj.bod

[cyhy]
bastion.mcdonnnj.cyhy
dashboard.mcdonnnj.cyhy
database1.mcdonnnj.cyhy
portscan[1:4].mcdonnnj.cyhy
reporter.mcdonnnj.cyhy
vulnscan1.mcdonnnj.cyhy
```

Parsed results from the CSV in the format `COMPUTER_NAME :: LAST_SCAN_TIME`:

```log
bastion :: 03/11/2021 06:25:17
bastion :: 03/11/2021 06:25:15
docker :: 03/11/2021 06:25:12
dashboard :: 03/11/2021 06:41:57
database1 :: 03/11/2021 06:35:07
portscan2 :: 03/11/2021 06:32:22
portscan1 :: 03/11/2021 06:32:09
portscan3 :: 03/11/2021 06:32:06
portscan4 :: 03/11/2021 06:31:55
reporter :: 03/11/2021 06:25:12
vulnscan1 :: 03/11/2021 06:41:31
```

## ✅ Checklist ##

* [x] This PR has an informative and human-readable title.
* [x] Changes are limited to a single goal - _eschew scope creep!_
* [x] All relevant type-of-change labels have been added.
* [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
* [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
* [x] All new and existing tests pass.

### CODE REVIEW

**Review by dav3r — APPROVED** [review]
Looks great to me- thanks for tackling this!  🗜️ 

Though I don't understand why the scanner instances in your test environment didn't execute their ClamAV scans, but the other instance types did.  Can you please clarify?

**Review by hillaryj — APPROVED** [review]
🐚

**Review by jsf9k — APPROVED** [review]
You make it look easy!

**Comment by mcdonnnj** [comment]
> 
> 
> Looks great to me- thanks for tackling this! 🗜️
> 
> Though I don't understand why the scanner instances in your test environment didn't execute their ClamAV scans, but the other instance types did. Can you please clarify?

@dav3r The scanner instances weren't redeployed until this week, but the `cron.weekly` jobs run every Sunday. It was just a matter of missing the scan window. I copied the jobs to `cron.daily` and they all had scans run (and I updated the description to reflect the correct data).

**Pull request merged**
