### PR TITLE
Update deployment scripts

### PR DESCRIPTION
**Pull request by mcdonnnj**
#  #

## 🗣 Description ##

The main focus in this pull request is fixing the deployment scripts for the portscan and vulnscan instances so that they are functional. It also moves all bash scripts in the `terraform/` directory into the `terraform/scripts/` sub-directory. 

## 💭 Motivation and context ##

There were two main issues that required a fix:

- The way the Terraform state stored information about `aws_instance` resources changed to include the index in the resource address.
- When we unwound the dynamic modules while upgrading from Terraform 0.12 the portscan and vulnscan scripts were not updated with the correct resource address.

Since we no longer use dynamic modules I also eliminated the second call to `terraform` for the database deployment script as the Ansible provisioner module now properly depends on the corresponding `aws_instance` resource.

## 🧪 Testing ##

Automated tests pass. I was able to use these updated scripts to successfully redeploy instances in my testing environment.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All new and existing tests pass.

### CODE REVIEW

**Review by jsf9k — APPROVED** [review]
The code changes look good to me, but I couldn't parse the run-on sentence in the "Motivation" section of the PR description.  Can you edit that to make it clearer?

**Comment by mcdonnnj** [comment]
> The code changes look good to me, but I couldn't parse the run-on sentence in the "Motivation" section of the PR description. Can you edit that to make it clearer?

Please let me know if it's still unclear after my revision. Apologies for the stream of consciousness I subjected you to initially.

**Comment by jsf9k** [comment]
> Please let me know if it's still unclear after my revision. Apologies for the stream of consciousness I subjected you to initially.

No problem.  It's clear now; before, I was worried that somebody had slipped me a mickey!

**Review by dav3r — APPROVED** [review]
Marvelous! 🎩

**Pull request merged**
