### PR TITLE
Move LGTM directive to the correct line

### PR DESCRIPTION
**Pull request by jsf9k**

### CODE REVIEW

**Review by dav3r — APPROVED** [review]
Unreach for the stars! 
⭐️ ⭐️ ⭐️

**Comment by jsf9k** [comment]
Whoa there, @dav3r!  Let's let the LGTM check run and see if this actually fixes anything first!

You're jumping the :gun:, but I appreciate your blind faith in me.

**Comment by dav3r** [comment]
Perhaps our policy in cases like this should be to create the PR, but not assign any reviewers until after the checks have completed.

**Comment by jsf9k** [comment]
Well that's what I did, sir!

**Comment by dav3r** [comment]
LOL, then I guess I should read my notifications a bit more closely! 😨

**Pull request merged**
