### PR TITLE
Add a Fourth vulnscan Instance to the Production Environment

### PR DESCRIPTION
**Pull request by mcdonnnj**
#  #

## 🗣 Description ##

This PR adds a fourth `vulnscan` instance to the CyHy environment.

## 💭 Motivation and Context ##

@dav3r mentioned wanting to add another Nessus scanner (`vulnscan` instance) to the environment. This will allow us to handle increased load, and look at lightening the per-instance load. We would need to update https://github.com/cisagov/cyhy_amis/blob/1dd200561bf7cdf7e083ed483cfa86a420557860/ansible/roles/cyhy_commander/files/commander.conf#L19 to adjust the load per instance if we wanted to go down that route. We could also look at the [cyhy-commander configuration for IPs per VULNSCAN](https://github.com/jsf9k/cyhy-commander/blob/f7574474498caf32261725b63735ebcc208b1409/cyhy_commander/commander.py#L108).

## 🧪 Testing ##

No testing at this point, but since this is just an instance addition it should be a clean deployment using our existing tooling.

## ✅ Checklist ##

* [x] This PR has an informative and human-readable title.
* [x] Changes are limited to a single goal - _eschew scope creep!_
* [x] All relevant type-of-change labels have been added.
* [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
* [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
* [x] All new and existing tests pass.

### CODE REVIEW

**Review by hillaryj — APPROVED** [review]
👍🏻

**Review by jsf9k — APPROVED** [review]
`++vulnscanners`

**Review by dav3r — APPROVED** [review]
Looks great- thanks for doing this! 🖖

**Comment by mcdonnnj** [comment]
This will be merged next week before deploying the new instance. I have added a `blocked` label until that time.

**Pull request merged**
