### PR TITLE
Update for use with Terraform 0.12

### PR DESCRIPTION
**Pull request by jsf9k**

### CODE REVIEW

**Comment by KyleEvers** [comment]
Is the aligning of variable assignments a style or functionality change?

**Comment by dav3r** [comment]
> Is the aligning of variable assignments a style or functionality change?

It's just a style thang- our terraform linter prefers that style of formatting.

**Comment by jsf9k** [comment]
> Is the aligning of variable assignments a style or functionality change?

It's a style change that `terraform 0.12upgrade` imposed.  Once we start using the skeletons here `terraform lint` will impose the same changes anyway.

**Review by dav3r — APPROVED** [review]
This all looks good.  I also spot-checked all of the instances in our `t12` testing workspace and I didn't see anything that looked out-of-whack.
💪 💪 work!

**Pull request merged**
