### PR TITLE
Modernize the Ansible roles used in the Terraform configuration

### PR DESCRIPTION
**Pull request by mcdonnnj**
#  #

## 🗣 Description ##

This pull request modernizes the Ansible roles we use in our Terraform configuration. This modernization updates them to more closely resemble our `cisagov/ansible-role-*` roles.

## 💭 Motivation and context ##

We currently do not perform any linting of these Ansible roles. Modernizing them not only makes sure they are written similarly to our `cisagov/ansible-role-*` roles but also allows us to enable the `ansible-lint` hook for `pre-commit`.

## 🧪 Testing ##

Automated tests pass. I used this branch in my [testing branch](https://github.com/cisagov/cyhy_amis/tree/testing/redeployment_updates) and was able to successfully deploy my instances. I checked the files on the production systems and in my testing environment and I am only seeing expected changes due to formatting, different regions, etc.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] Tests have been added and/or modified to cover the changes in this PR.
- [x] All new and existing tests pass.

### CODE REVIEW

**Review by jsf9k — APPROVED** [review]
These changes look good to me.  Nice cleanup!

**Review by dav3r — APPROVED** [review]
Looks great, strong work and thanks for taking care of this cleanup work!  ⭐

**Comment by mcdonnnj** [comment]
The force-pushes have had some changes wrapped up in them so I have re-requested reviews.

**Review by jsf9k — APPROVED** [review]
_Approval intensifies_

**Review by dav3r — APPROVED** [review]
Still fabulous. 🔥

**Pull request merged**
